src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $category;

    /**
     * @ORM\Column(type="integer")
     */
    private $view_count;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function getFiftyFistCharOfContent(): ?string
    {
        $result = substr($this->content, 1, 50);
        if ($result===false) 
            return null;
        else 
            return $result;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getViewCount(): ?int
    {
        return $this->view_count;
    }

    public function setViewCount(int $view_count): self
    {
        $this->view_count = $view_count;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Exception\RouteNotFoundException;
use App\Service\SwearCleaner;
use Doctrine\Persistence\ObjectManager;
use App\Entity\Article;
use App\Form\ArticleType;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="index")
     * @Route("/home", name="home")
     */
    public function index(): Response
    {
        $articleRepository = $this->getDoctrine()->getRepository(Article::class);
        $articles = $articleRepository->findLastArticles(3);
        // dump($articles);
        
        return $this->render('home/home.html.twig', [
            'articles' => $articles,
        ]);
    }

    /**
     * @Route("/article/{page<\d+>?1}", name="show_post")
     */
    public function showPost(int $page): Response
    {
        $articleRepository = $this->getDoctrine()->getRepository(Article::class);
        $article = $articleRepository->find($page);

        $swearCleaner = new  SwearCleaner();
        $article = $swearCleaner->cleanSwear($article);

        return $this->render('home/show.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/admin/article/add", name="add_post")
     */
    public function addPost(Request $request): Response
    {
        $article = new Article;
        $form = $this->CreateForm(ArticleType::class, $article);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // $article->setTitle('test');
            // $article->setContent('test');
            // $article->setAuthor('test');
            // $article->setDate(new \DateTime());
            // $article->setCategory('test');
            // $article->setViewCount(0);

            $article = $form->getdata();
            $em =$this->getDoctrine()->getManager();
            $em->persist($article);
            $em->flush();

            return $this->redirectToRoute('add_post');
        }

        return $this->render('home/add.html.twig', [
            'form' => $form->createView()
        ]);

        // return $this->render('home/add.html.twig', [
        //     'controller_name' => 'Ajouter Article',
        // ]);
    }
}

templates/home/add.html.twig
{% extends 'template.html.twig' %}

{% block title %}Blog Accueil{% endblock %}
{% block main %}
    {{ form(form) }}
{% endblock %}

templates/home/home.html.twig
{% extends 'template.html.twig' %}

{% block title %}Accueil{% endblock %}
{% block main %}


    <h2>Derniers articles</h2>
    {% for article in articles %}

        <div class="card my-3">
            <div class="card-header">
                <h5>Sujet : <a href={{ path("show_post") }}/{{article.id}}>{{article.title}}</a></h5>
            </div>
            <div class="card-body">
                <table class="table table-striped table-bordered table-sm">
                    <tbody>
                        <tr><th>Auteur</th><td>{{article.author}}</td></tr>
                        <tr><th>Date</th><td>{{article.date|date("m/d/Y H:i")}}</td></tr>
                        <tr><th>Nombre de vue</th><td>{{article.viewCount}}</td></tr>
                        <tr><th>Catégorie</th><td>{{article.category}}</td></tr>
                        <tr><th>Extrait</th><td>{{article.FiftyFistCharOfContent}}</td></tr>
                    </tbody>
                </table>
            </div>
        </div>
    {% endfor %}

{% endblock %}

templates/home/show.html.twig
{% extends 'template.html.twig' %}

{% block title %}Blog Accueil{% endblock %}
{% block main %}
    <div class="card my-3">
        <div class="card-header">
            <h5>Sujet : <a href={{ path("show_post") }}/{{article.id}}>{{article.title}}</a></h5>
        </div>
        <div class="card-body">
            <table class="table table-striped table-bordered table-sm">
                <tbody>
                    <tr><th>Auteur</th><td>{{article.author}}</td></tr>
                    <tr><th>Date</th><td>{{article.date|date("m/d/Y H:i")}}</td></tr>
                    <tr><th>Nombre de vue</th><td>{{article.viewCount}}</td></tr>
                    <tr><th>Catégorie</th><td>{{article.category}}</td></tr>
                    <tr><th>Contenu</th><td>{{article.content}}</td></tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}